const ENGAGEMENT={PENDING_PAYMENT:{payment_succeeded:'ACTIVE',payment_failed:'PAYMENT_FAILED',cancel:'CANCELLED'},PAYMENT_FAILED:{retry_payment:'PENDING_PAYMENT',cancel:'CANCELLED'},ACTIVE:{pause:'PAUSED',complete:'COMPLETED',cancel:'REFUND_PENDING'},PAUSED:{resume:'ACTIVE',cancel:'REFUND_PENDING'},REFUND_PENDING:{refund_succeeded:'CANCELLED',refund_failed:'REFUND_FAILED'},REFUND_FAILED:{retry_refund:'REFUND_PENDING'}};
const SESSION={VIDEO_PENDING:{video_succeeded:'CONFIRMED',provider_failed:'PROVIDER_FAILED',cancel:'CANCELLED'},PROVIDER_FAILED:{retry_video:'VIDEO_PENDING',cancel:'CANCELLED'},CONFIRMED:{complete:'COMPLETED',cancel:'CANCELLED'},COMPLETED:{acknowledge:'CLIENT_ACKNOWLEDGED'}};
function transition(map,current,command){const next=map[current]?.[command];if(!next)throw Object.assign(new Error(`Cannot ${command} while state is ${current}`),{status:409});return next;}
function engagementTransition(state,command){return transition(ENGAGEMENT,state,command);}function sessionTransition(state,command){return transition(SESSION,state,command);}
function positiveCents(value){if(!Number.isInteger(value)||value<1)throw Object.assign(new Error('priceCents must be a positive integer'),{status:400});return value;}
function progress(value){if(!Number.isInteger(value)||value<0||value>100)throw Object.assign(new Error('progress must be an integer from 0 to 100'),{status:400});return value;}
function canAccess(principal,engagement){return principal.role==='operator'||(principal.role==='client'&&engagement.client_subject===principal.subject)||(principal.role==='coach'&&engagement.coach_subject===principal.subject);}
function outcomeSummary(goals,checkIns){const active=goals.filter(g=>g.status==='ACTIVE');const average=active.length?Math.round(active.reduce((sum,g)=>sum+g.progress,0)/active.length):0;const latest=checkIns[0];return{activeGoals:active.length,averageProgress:average,latestEvidence:latest?.evidence||null,latestConfidence:latest?.confidence??null,method:'deterministic-recorded-outcomes'};}
module.exports={ENGAGEMENT,SESSION,engagementTransition,sessionTransition,positiveCents,progress,canAccess,outcomeSummary};
